"""empty message

Revision ID: 6305fc83dfd7
Revises: 43e027aa5ff8
Create Date: 2023-12-20 14:38:17.102662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6305fc83dfd7"
down_revision: Union[str, None] = "43e027aa5ff8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "roles", ["id"])
    op.create_unique_constraint(None, "users", ["id"])
    op.alter_column(
        "visits",
        "user_agent",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=5),
        existing_nullable=True,
    )
    op.create_unique_constraint(None, "visits", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "visits", type_="unique")
    op.alter_column(
        "visits",
        "user_agent",
        existing_type=sa.String(length=5),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "roles", type_="unique")
    # ### end Alembic commands ###
