"""empty message

Revision ID: 73ef3feb9d69
Revises: 6305fc83dfd7
Create Date: 2023-12-20 15:06:23.171340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73ef3feb9d69"
down_revision: Union[str, None] = "6305fc83dfd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "visits",
        "user_agent",
        existing_type=sa.VARCHAR(length=5),
        type_=sa.String(length=500),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "visits",
        "user_agent",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=5),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
